"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*oshou5_lk_e$mxgmny!m1yt_tticvj4&%49gj06cpa&2t*%n%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'bookshelf',
     'relationship_app',
     'csp',  # Content Security Policy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy - must be early
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model Configuration
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Media files configuration (for profile photos)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# SECURITY SETTINGS - BEST PRACTICES IMPLEMENTATION
# =============================================================================

# BEGINNER EXPLANATION:
# These settings protect your Django application from common security vulnerabilities.
# Each setting serves a specific purpose in hardening your application.

# 1. CROSS-SITE REQUEST FORGERY (CSRF) PROTECTION
# ================================================
# CSRF tokens prevent malicious sites from submitting forms to your site
CSRF_COOKIE_SECURE = True  # Only send CSRF cookies over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = 'Strict'  # Strict same-site policy for CSRF cookies
CSRF_USE_SESSIONS = True  # Store CSRF token in session instead of cookie

# 2. SESSION SECURITY
# ===================
# Sessions store user login information - must be protected
SESSION_COOKIE_SECURE = True  # Only send session cookies over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # Strict same-site policy for session cookies
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # End session when browser closes
SESSION_COOKIE_AGE = 3600  # Session expires after 1 hour (3600 seconds)

# 3. SECURE HEADERS
# =================
# These headers tell browsers how to handle your site securely
SECURE_BROWSER_XSS_FILTER = True  # Enable browser's XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevent your site from being embedded in frames
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control referrer information

# 4. HTTPS/SSL SECURITY
# =====================
# Force HTTPS for all connections (comment out for development)
# SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
# SECURE_HSTS_SECONDS = 31536000  # HTTP Strict Transport Security (1 year)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to subdomains
# SECURE_HSTS_PRELOAD = True  # Allow browser preloading of HSTS

# NOTE: HTTPS settings are commented out for development.
# UNCOMMENT these when deploying to production with proper SSL certificate.

# 5. DEVELOPMENT VS PRODUCTION SECURITY
# =====================================
# In development, we need to allow some insecure practices for testing
if DEBUG:
    # Development settings - less restrictive for testing
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']  # Added testserver for testing
    
    # Add security warning for development
    import warnings
    warnings.warn(
        "🚨 SECURITY WARNING: This application is running in DEBUG mode. "
        "Do NOT deploy to production with DEBUG=True!",
        UserWarning
    )
else:
    # Production settings - maximum security
    ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']  # Set your actual domain
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# 6. CONTENT SECURITY POLICY (CSP)
# =================================
# CSP prevents XSS attacks by controlling which resources can be loaded
# Updated to use django-csp 4.0+ format
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),           # Only allow resources from same origin
        'script-src': ("'self'", "'unsafe-inline'"),  # Allow inline scripts (be careful!)
        'style-src': ("'self'", "'unsafe-inline'"),   # Allow inline styles
        'img-src': ("'self'", "data:"),       # Allow images from same origin and data URLs
        'font-src': ("'self'",),              # Only allow fonts from same origin
    }
}

# 7. SECURITY LOGGING
# ===================
# Log security events for monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
