"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*oshou5_lk_e$mxgmny!m1yt_tticvj4&%49gj06cpa&2t*%n%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'bookshelf',
     'relationship_app',
     'csp',  # Content Security Policy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy - must be early
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model Configuration
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Media files configuration (for profile photos)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# SECURITY SETTINGS - BEST PRACTICES IMPLEMENTATION
# =============================================================================

# BEGINNER EXPLANATION:
# These settings protect your Django application from common security vulnerabilities.
# Each setting serves a specific purpose in hardening your application.

# 1. CROSS-SITE REQUEST FORGERY (CSRF) PROTECTION
# ================================================
# CSRF tokens prevent malicious sites from submitting forms to your site
CSRF_COOKIE_SECURE = True  # Only send CSRF cookies over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = 'Strict'  # Strict same-site policy for CSRF cookies
CSRF_USE_SESSIONS = True  # Store CSRF token in session instead of cookie

# 2. SESSION AND COOKIE SECURITY
# ===============================
# Sessions store user login information and must be protected
# Cookies can contain sensitive data and require secure transmission

# Session Cookie Security
SESSION_COOKIE_SECURE = not DEBUG  # Only send session cookies over HTTPS (auto-enable in production)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie (XSS protection)
SESSION_COOKIE_SAMESITE = 'Strict'  # Strict same-site policy for session cookies (CSRF protection)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # End session when browser closes
SESSION_COOKIE_AGE = 3600  # Session expires after 1 hour (3600 seconds)
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name
SESSION_SAVE_EVERY_REQUEST = False  # Only save session if modified (performance)

# CSRF Cookie Security
CSRF_COOKIE_SECURE = not DEBUG  # Only send CSRF cookies over HTTPS (auto-enable in production)
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = 'Strict'  # Strict same-site policy for CSRF cookies
CSRF_COOKIE_AGE = 31449600  # CSRF cookie expires after 1 year
CSRF_USE_SESSIONS = True  # Store CSRF token in session instead of cookie (more secure)
CSRF_COOKIE_NAME = 'csrftoken'  # Default CSRF cookie name

# Additional Cookie Security Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store sessions in database
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'  # Use JSON serializer

# Security Note: In production with HTTPS:
# - SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE should be True
# - This ensures cookies are only transmitted over encrypted connections
# - In development (DEBUG=True), these are set to False for local testing

# 3. SECURE HTTP HEADERS
# =======================
# Security headers instruct browsers on how to handle your site securely
# These headers provide defense against various attack vectors

# XSS (Cross-Site Scripting) Protection
SECURE_BROWSER_XSS_FILTER = True  # Enable browser's built-in XSS filtering
# Note: This header is deprecated in modern browsers but kept for legacy support

# MIME Type Security
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent browsers from MIME-sniffing responses
# This prevents browsers from trying to guess content types, which can lead to security issues

# Clickjacking Protection
X_FRAME_OPTIONS = 'DENY'  # Prevent your site from being embedded in frames/iframes
# Options: 'DENY' (never allow framing), 'SAMEORIGIN' (allow same-origin framing)

# Referrer Policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Controls how much referrer information is included with requests
# 'strict-origin-when-cross-origin': Send full URL for same-origin, origin only for cross-origin HTTPS

# Additional Security Headers (custom implementation in middleware or views)
# These can be added via custom middleware for more granular control:
SECURITY_HEADERS = {
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'geolocation=(), microphone=(), camera=()',  # Feature Policy
}

# Content Security Policy is configured separately below
# These headers work together to create multiple layers of security

# 4. HTTPS/SSL SECURITY
# =====================
# These settings enforce HTTPS connections and implement security best practices
# for secure web communication

# Production HTTPS Settings (enable in production)
# SECURE_SSL_REDIRECT: Redirects all HTTP requests to HTTPS
# Set to True in production to enforce HTTPS-only access
SECURE_SSL_REDIRECT = not DEBUG  # Auto-enable in production

# HTTP Strict Transport Security (HSTS)
# Tells browsers to only access this site via HTTPS for the specified duration
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production, disabled in dev
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS policy to all subdomains
SECURE_HSTS_PRELOAD = True  # Allow browsers to preload HSTS for this domain

# Secure Proxy Headers
# Important for deployment behind reverse proxies (nginx, load balancers)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional HTTPS Security Settings
SECURE_SSL_HOST = None  # Redirect to specific host if needed
SECURE_REDIRECT_EXEMPT = []  # URLs exempt from HTTPS redirect (use sparingly)

# NOTE: When deploying to production:
# 1. Ensure SSL certificate is properly configured on your web server
# 2. Update ALLOWED_HOSTS with your actual domain names
# 3. Test HTTPS redirect functionality
# 4. Monitor HSTS header implementation

# 5. ENVIRONMENT-SPECIFIC SECURITY CONFIGURATION
# ===============================================
# Different security settings for development vs production environments

if DEBUG:
    # DEVELOPMENT ENVIRONMENT SETTINGS
    # ================================
    # Less restrictive settings for local development and testing
    
    # Allow local development hosts
    ALLOWED_HOSTS = [
        '127.0.0.1', 
        'localhost', 
        'testserver',  # For Django testing
        '0.0.0.0',     # For Docker development
    ]
    
    # Disable HTTPS requirements for local development
    # (These are automatically managed by the settings above)
    
    # Development-specific security relaxations
    SECURE_SSL_REDIRECT = False  # Allow HTTP in development
    
    # Add security warning for development mode
    import warnings
    warnings.warn(
        "🚨 SECURITY WARNING: This application is running in DEBUG mode. "
        "Do NOT deploy to production with DEBUG=True! "
        "HTTPS enforcement is disabled for local development.",
        UserWarning
    )
    
else:
    # PRODUCTION ENVIRONMENT SETTINGS
    # ===============================
    # Maximum security configuration for production deployment
    
    # Production domain configuration
    # UPDATE THESE WITH YOUR ACTUAL DOMAIN NAMES
    ALLOWED_HOSTS = [
        'yourdomain.com',           # Replace with your domain
        'www.yourdomain.com',       # Replace with your www domain
        'api.yourdomain.com',       # Add any subdomains you use
        # Add your production server IP if needed
    ]
    
    # Force HTTPS in production
    SECURE_SSL_REDIRECT = True
    
    # Additional production security measures
    SECURE_HSTS_SECONDS = 31536000  # 1 year HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Production-specific settings
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', SECRET_KEY)  # Use environment variable
    
    # Additional production recommendations:
    # 1. Use environment variables for sensitive settings
    # 2. Set up proper SSL certificates (Let's Encrypt, commercial CA)
    # 3. Configure your web server (nginx/Apache) for HTTPS
    # 4. Implement monitoring and alerting for security events
    # 5. Regular security audits and dependency updates

# 6. CONTENT SECURITY POLICY (CSP)
# =================================
# CSP prevents XSS attacks by controlling which resources can be loaded
# Updated to use django-csp 4.0+ format
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),           # Only allow resources from same origin
        'script-src': ("'self'", "'unsafe-inline'"),  # Allow inline scripts (be careful!)
        'style-src': ("'self'", "'unsafe-inline'"),   # Allow inline styles
        'img-src': ("'self'", "data:"),       # Allow images from same origin and data URLs
        'font-src': ("'self'",),              # Only allow fonts from same origin
    }
}

# 7. SECURITY LOGGING
# ===================
# Log security events for monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
