# Generated by Django 5.2.4 on 2025-07-24 19:18

from django.db import migrations

def create_custom_permissions(apps, schema_editor):
    """Create custom permissions for Product model"""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Product = apps.get_model('book_store', 'Product')
    
    content_type = ContentType.objects.get_for_model(Product)
    
    # Create missing custom permission
    Permission.objects.get_or_create(
        codename='can_delete_product',
        name='Can delete products',
        content_type=content_type,
    )

def reverse_custom_permissions(apps, schema_editor):
    """Remove custom permissions"""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Product = apps.get_model('book_store', 'Product')
    
    content_type = ContentType.objects.get_for_model(Product)
    Permission.objects.filter(
        codename='can_delete_product',
        content_type=content_type,
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_custom_permissions, reverse_custom_permissions),
    ]
