# Generated by Django 5.2.4 on 2025-07-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_auto_20250724_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_all_products', 'Can view all products'), ('can_manage_inventory', 'Can manage inventory'), ('can_set_prices', 'Can set product prices'), ('can_delete_product', 'Can delete products')]},
        ),
    ]
